### ISSUE TITLE
rails new

### ISSUE THREAD

**Issue by YuyaYamada0602** [YuyaYamada0602/go#1]
## rails new
- [x] `rails new go --webpack=react --database=postgresql --api`

## rbenv
- [x] `rbenv local 2.5.1 `
## Docker
- [x] Dockerfile
```
FROM ruby:2.5.1
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /go
WORKDIR /go
COPY Gemfile /go/Gemfile
COPY Gemfile.lock /go/Gemfile.lock
RUN bundle install
COPY . /go
RUN heroku container:login
RUN heroku create
RUN heroku container:push
RUN heroku container:release web
RUN heroku container:pull web
RUN heroku open
```
- [x] docker-compose.yml
```
version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/go
    ports:
      - "3000:3000"
    depends_on:
      - db
```
- [x] docker command
```
docker-compose build

docker-compose up
```
## heroku
- [x] heroku create
```
# heroku-cliのインストール
brew install heroku/brew/heroku

# heroku-cliのバージョン確認
heroku —version

# herokuにログイン
heroku login

# 鍵の追加
heroku keys:add

# コンテナ用のプラグインを追加
heroku plugins:install @heroku-cli/plugin-container-registry

# コンテナにログイン
heroku container:login

# アプリの作成（作成されたアプリ名称を控えておく）
heroku create

# herokuに設定を追加
SECRET_BASE_KEY=$(docker-compose run api rails secret)
heroku config:add SECRET_KEY_BASE=$SECRET_BASE_KEY -a {your_heroku_app_name}

# コンテナをデプロイ
heroku container:push web -a {your_heroku_app_name}

# PostgreSQLのアドオンを追加
heroku addons:create heroku-postgresql:hobby-dev -a {your_heroku_app_name}

# テーブルの作成
heroku run rails db:migrate -a {your_heroku_app_name}

# シードの反映
heroku run rails db:seed -a {your_heroku_app_name}
```
## Circle CI
- [x] circle.yml
```
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: "before_test: setup db"
          command: docker-compose run web rails db:create db:migrate
      - run:
          name: test
          command: docker-compose run web rspec
      - run:
          name: docker-compose down
          command: docker-compose down
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # see: https://devcenter.heroku.com/articles/container-registry-and-runtime#using-a-ci-cd-platform
      - run:
          name: "build docker image"
          command: docker build --rm=false -t registry.heroku.com/go-inc/web .
      - run:
          name: setup heroku command
          command: bash .circleci/setup_heroku.sh
      - run:
          name: heroku maintenance on
          command: heroku maintenance:on --app go-inc
      - run:
        # HEROKU_AUTH_TOKEN is generated by `heroku auth:token`
          name: "push container to registry.heroku.com"
          command: |
            docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
            docker push registry.heroku.com/go-inc/web
      - run:
          name: heroku db migrate
          command: heroku run rails db:migrate --app go-inc
      - run:
          name: heroku maintenance off
          command: heroku maintenance:off --app go-inc
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
```
