### ISSUE TITLE
Docker導入

### ISSUE THREAD

**Issue by YuyaYamada0602** [YuyaYamada0602/Go#1]
## Dockerfileを設定
```
ex) rails

FROM ruby:2.5.1
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /go
WORKDIR /go
COPY Gemfile /go/Gemfile
COPY Gemfile.lock /go/Gemfile.lock
RUN bundle install
COPY . /go
```
## docker-compose.ymlで各コンテナを連結させる
```
ex) rails db:postgresql

version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/go
    ports:
      - "3000:3000"
    depends_on:
      - db
```
```
## appをdocker-compose上にビルドする
$ docker-compose build
```
```
## app 起動
docker-compose up
```
